force-app/main/default/objects/MobileDevise__c/MobileDevise__c.object-meta.xml
<CustomObject>
    <description>モバイルデバイス</description>
    <label>MobileDevise</label>
    <nameField>
        <label>MobileDevise</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MobileDevise__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>参照先となる取引先責任者</description>
    <inlineHelpText>テストで生成</inlineHelpText>
    <label>取引先責任者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MobileDevise</relationshipLabel>
    <relationshipName>MobileDevise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/MobileDeviceController.cls
/**
 * Created by ynaka on 2025/05/27.
 */

public with sharing class MobileDeviceController {
  public static final String EXCEPTION_EMPTY_CONTACT = 'ContactId is required.';
  public static final String INVALID_CONTACT_ID = 'Invalid ContactId format.';

  @AuraEnabled
  public static List<MobileDevise__c> findMobileDeviceByContact(String contactId) {
    if (String.isBlank(contactId)) throw new AuraHandledException(EXCEPTION_EMPTY_CONTACT);

    try {
      Id validContactId = Id.valueOf(contactId);
      return [
          SELECT Id, Name
          FROM MobileDevise__c
          WHERE Contact__c = :validContactId
      ];
    }
    catch (Exception e) {
      throw new AuraHandledException(INVALID_CONTACT_ID);
    }
  }
}